RENAME TABLE inf_account_inf_account_type TO account_account_type ;
RENAME TABLE inf_account_types TO account_types ;
RENAME TABLE inf_accounts TO accounts ;
RENAME TABLE inf_address_types TO address_types ;
RENAME TABLE inf_addresses TO addresses ;
RENAME TABLE inf_communication_types TO communication_types ;
RENAME TABLE inf_contact_detail_types TO contact_detail_types ;
RENAME TABLE inf_contact_details TO contact_details ;
RENAME TABLE inf_contact_types TO contact_types ;
RENAME TABLE inf_contacts TO contacts ;
RENAME TABLE inf_document_statuses TO document_statuses ;
RENAME TABLE inf_document_types TO document_types ;
RENAME TABLE inf_documents TO documents ;
RENAME TABLE inf_event_inf_event_type TO event_event_type ;
RENAME TABLE inf_event_results TO event_results ;
RENAME TABLE inf_event_statuses TO event_statuses ;
RENAME TABLE inf_event_types TO event_types ;
RENAME TABLE inf_events TO events ;
RENAME TABLE inf_localities TO localities ;
RENAME TABLE inf_offices TO offices ;
RENAME TABLE inf_opportunities TO opportunities ;
RENAME TABLE inf_opportunity_inf_opportunity_type TO opportunity_opportunity_type ;
RENAME TABLE inf_opportunity_results TO opportunity_results ;
RENAME TABLE inf_opportunity_statuses TO opportunity_statuses ;
RENAME TABLE inf_opportunity_types TO opportunity_types ;
RENAME TABLE inf_service_ticket_inf_service_ticket_type TO service_ticket_service_ticket_type ;
RENAME TABLE inf_service_ticket_results TO service_ticket_results ;
RENAME TABLE inf_service_ticket_statuses TO service_ticket_statuses ;
RENAME TABLE inf_service_ticket_types TO service_ticket_types ;
RENAME TABLE inf_service_tickets TO service_tickets ;
RENAME TABLE inf_titles TO titles ;
RENAME TABLE inf_web_site_types TO web_site_types ;
RENAME TABLE inf_web_sites TO web_sites ;

ALTER TABLE accounts CHANGE inf_title_id title_id int(10) unsigned NULL ;
ALTER TABLE accounts DROP FOREIGN KEY inf_accounts_inf_title_id_foreign ;
ALTER TABLE accounts ADD CONSTRAINT accounts_titles_FK FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE SET NULL ON UPDATE CASCADE ;

ALTER TABLE web_sites DROP FOREIGN KEY inf_web_sites_inf_web_site_type_id_foreign ;
ALTER TABLE web_sites DROP FOREIGN KEY inf_web_sites_inf_account_id_foreign ;
ALTER TABLE web_sites CHANGE inf_web_site_type_id web_site_type_id int(10) unsigned NOT NULL ;
ALTER TABLE web_sites CHANGE inf_account_id account_id int(10) unsigned NOT NULL ;
ALTER TABLE web_sites ADD CONSTRAINT web_sites_web_site_types_FK FOREIGN KEY (web_site_type_id) REFERENCES web_site_types(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE web_sites ADD CONSTRAINT web_sites_accounts_FK FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE addresses DROP FOREIGN KEY inf_addresses_inf_account_id_foreign ;
ALTER TABLE addresses DROP FOREIGN KEY inf_addresses_inf_address_type_id_foreign ;
ALTER TABLE addresses CHANGE inf_address_type_id address_type_id int(10) unsigned NULL ;
ALTER TABLE addresses CHANGE inf_account_id account_id int(10) unsigned NULL ;
ALTER TABLE addresses ADD CONSTRAINT addresses_address_types_FK FOREIGN KEY (address_type_id) REFERENCES address_types(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE addresses ADD CONSTRAINT addresses_accounts_FK FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE ;


ALTER TABLE contacts DROP FOREIGN KEY inf_contacts_inf_title_id_foreign ;
ALTER TABLE contacts DROP FOREIGN KEY inf_contacts_inf_office_id_foreign ;
ALTER TABLE contacts DROP FOREIGN KEY inf_contacts_inf_contact_type_id_foreign ;
ALTER TABLE contacts DROP FOREIGN KEY inf_contacts_inf_account_id_foreign ;
ALTER TABLE contacts CHANGE inf_title_id title_id int(10) unsigned NULL ;
ALTER TABLE contacts CHANGE inf_account_id account_id int(10) unsigned NULL ;
ALTER TABLE contacts CHANGE inf_contact_type_id contact_type_id int(10) unsigned NULL ;
ALTER TABLE contacts CHANGE inf_office_id office_id int(10) unsigned NULL ;
ALTER TABLE contacts ADD CONSTRAINT contacts_titles_FK FOREIGN KEY (title_id) REFERENCES titles(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE contacts ADD CONSTRAINT contacts_accounts_FK FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE ;
ALTER TABLE contacts ADD CONSTRAINT contacts_contact_types_FK FOREIGN KEY (contact_type_id) REFERENCES contact_types(id) ON DELETE RESTRICT ON UPDATE RESTRICT ;
ALTER TABLE contacts ADD CONSTRAINT contacts_offices_FK FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE RESTRICT ON UPDATE CASCADE ;

ALTER TABLE contact_details DROP FOREIGN KEY inf_contact_details_inf_communication_type_id_foreign ;
ALTER TABLE contact_details DROP FOREIGN KEY inf_contact_details_inf_contact_detail_type_id_foreign ;
ALTER TABLE contact_details DROP FOREIGN KEY inf_contact_details_inf_contact_id_foreign ;
ALTER TABLE contact_details CHANGE inf_contact_id contact_id int(10) unsigned NULL ;
ALTER TABLE contact_details CHANGE inf_contact_detail_type_id contact_detail_type_id int(10) unsigned NULL ;
ALTER TABLE contact_details CHANGE inf_communication_type_id communication_type_id int(10) unsigned NULL ;
ALTER TABLE contact_details ADD CONSTRAINT contact_details_contacts_FK FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE ON UPDATE CASCADE ;
ALTER TABLE contact_details ADD CONSTRAINT contact_details_contact_detail_types_FK FOREIGN KEY (contact_detail_type_id) REFERENCES contact_detail_types(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE contact_details ADD CONSTRAINT contact_details_communication_types_FK FOREIGN KEY (communication_type_id) REFERENCES communication_types(id) ON DELETE RESTRICT ON UPDATE CASCADE ;

ALTER TABLE events DROP FOREIGN KEY inf_events_inf_account_id_foreign ;
ALTER TABLE events DROP FOREIGN KEY inf_events_inf_event_result_id_foreign ;
ALTER TABLE events DROP FOREIGN KEY inf_events_inf_event_status_id_foreign ;
ALTER TABLE events DROP FOREIGN KEY inf_events_inf_opportunity_id_foreign ;
ALTER TABLE events CHANGE inf_account_id account_id int(10) unsigned NOT NULL ;
ALTER TABLE events CHANGE inf_event_status_id event_status_id int(10) unsigned NOT NULL ;
ALTER TABLE events CHANGE inf_event_result_id event_result_id int(10) unsigned NULL ;
ALTER TABLE events CHANGE inf_opportunity_id opportunity_id int(10) unsigned NULL ;
ALTER TABLE events ADD CONSTRAINT events_accounts_FK FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE ;
ALTER TABLE events ADD CONSTRAINT events_event_statuses_FK FOREIGN KEY (event_status_id) REFERENCES event_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE events ADD CONSTRAINT events_event_results_FK FOREIGN KEY (event_result_id) REFERENCES event_results(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE events ADD CONSTRAINT events_opportunities_FK FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE ON UPDATE CASCADE ;

ALTER TABLE opportunities DROP FOREIGN KEY inf_opportunities_inf_account_id_foreign ;
ALTER TABLE opportunities DROP FOREIGN KEY inf_opportunities_inf_opportunity_result_id_foreign ;
ALTER TABLE opportunities DROP FOREIGN KEY inf_opportunities_inf_opportunity_status_id_foreign ;
ALTER TABLE opportunities CHANGE inf_account_id account_id int(10) unsigned NULL ;
ALTER TABLE opportunities CHANGE inf_opportunity_status_id opportunity_status_id int(10) unsigned NULL ;
ALTER TABLE opportunities CHANGE inf_opportunity_result_id opportunity_result_id int(10) unsigned NULL ;
ALTER TABLE opportunities ADD CONSTRAINT opportunities_accounts_FK FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE ;
ALTER TABLE opportunities ADD CONSTRAINT opportunities_opportunity_statuses_FK FOREIGN KEY (opportunity_status_id) REFERENCES opportunity_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE opportunities ADD CONSTRAINT opportunities_opportunity_results_FK FOREIGN KEY (opportunity_result_id) REFERENCES opportunity_results(id) ON DELETE RESTRICT ON UPDATE CASCADE ;

ALTER TABLE service_tickets DROP FOREIGN KEY inf_service_tickets_inf_account_id_foreign ;
ALTER TABLE service_tickets DROP FOREIGN KEY inf_service_tickets_inf_service_ticket_result_id_foreign ;
ALTER TABLE service_tickets DROP FOREIGN KEY inf_service_tickets_inf_service_ticket_status_id_foreign ;
ALTER TABLE service_tickets DROP FOREIGN KEY inf_service_tickets_user_id_foreign ;
ALTER TABLE service_tickets CHANGE inf_account_id account_id int(10) unsigned NULL ;
ALTER TABLE service_tickets CHANGE inf_service_ticket_status_id service_ticket_status_id int(10) unsigned NULL ;
ALTER TABLE service_tickets CHANGE inf_service_ticket_result_id service_ticket_result_id int(10) unsigned NULL ;
ALTER TABLE service_tickets ADD CONSTRAINT service_tickets_accounts_FK FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE ;
ALTER TABLE service_tickets ADD CONSTRAINT service_tickets_users_FK FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE service_tickets ADD CONSTRAINT service_tickets_service_ticket_statuses_FK FOREIGN KEY (service_ticket_status_id) REFERENCES service_ticket_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
ALTER TABLE service_tickets ADD CONSTRAINT service_tickets_service_ticket_results_FK FOREIGN KEY (service_ticket_result_id) REFERENCES service_ticket_results(id) ON DELETE RESTRICT ON UPDATE CASCADE ;
